version: '3'
services:
  auth-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MAINTENANCE_MODE=false
      - AUTH_MODE=HOME
    volumes:
      - ./db.sqlite3:/app/db.sqlite3